# Generated by Django 5.2 on 2025-04-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_message_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
